workflows:
  flutter_web_build:
    name: Flutter Web Build
    environment:
      flutter: stable
    scripts:
      - name: Create fresh Flutter Web project
        script: |
          flutter create parking_app
          cp ~/main_backup.dart parking_app/lib/main.dart
      - name: Get dependencies
        script: |
          cd parking_app
          flutter pub get
      - name: Build Flutter Web
        script: |
          cd parking_app
          flutter build web --release --web-renderer html
    artifacts:
      - parking_app/build/web
    publishing:
      web: true
